"""Embed README.md content into js/readme-data.js as a string constant.

Loading the dashboard via file:// would otherwise fail because browsers
block fetch() of local files due to CORS. Embedding the markdown into a
script tag sidesteps the fetch entirely.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "README.md"
OUT = ROOT / "js" / "readme-data.js"


def main():
    text = SRC.read_text(encoding="utf-8")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Auto-generated by scripts/build_readme_js.py - do not edit by hand.\n"
        "// Source: README.md (kept in sync at build time so the dashboard works\n"
        "// when opened via file:// without a web server).\n\n"
        "const README_MD = " + json.dumps(text) + ";\n"
    )
    print(f"Wrote {OUT} ({OUT.stat().st_size/1024:.1f} KB)")


if __name__ == "__main__":
    main()
